name: Prettier Action
description: Automatically runs prettier on all your changes.

author: Conrad Großer <grosserconrad@gmail.com>

inputs:
  prettier_options:
    description: Options for the `prettier` command
    required: false
    default: '--write **/*.js'

runs:
  using: 'docker'
  image: 'Dockerfile'

branding:
  icon: 'award'
  color: 'green'
