name: Prettier Action
description: Automatically runs prettier on all your changes.

author: Conrad Großer <grosserconrad@gmail.com>

inputs:
  prettier_options:
    description: Options for the `prettier` command
    required: false
    default: '--write **/*.js'

runs:
  using: 'composite'
  steps:
    - name: install prettier
      shell: bash
      run: (cd $GITHUB_ACTION_PATH; npm install --silent prettier)
    - name: prettier
      shell: bash
      run: >-
        PATH=$(cd $GITHUB_ACTION_PATH; npm bin):$PATH
        shopt -s globstar nullglob
        prettier
        ${{ inputs.prettier_options }}

branding:
  icon: 'award'
  color: 'green'
